id: I5A7D2DEE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:11:46+00:00'
last_modified: '2022-06-08T06:08:02.341342+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17626
  title: '汉英－英汉藏学翻译词典

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0A34:
      image_group_id: I4PD4265
      title: ''
      total_pages: 1204
      order: 1
      base_file: 0A34.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
